### PR TITLE
Enhanced Scaling

### PR DESCRIPTION
**Pull request by ToruTheRedFox**
Sonic CD is COMIN' SOON

just gotta get it to the same standard as this one lol

### CODE REVIEW

**Comment by Xeeynamo** [comment]
Hey :) I would love to see a screenshot as comparison to understand the impact of this PR, if you don't mind. Also you might want to re-base your branch and do a `git push --force-with-lease` as there are few conflicts with the latest codebase.

**Comment by ToruTheRedFox** [comment]
I use Github Desktop to push things so I'm not sure how to do that there

and the differences are detailed in the corresponding issue that I opened about this (basically it scales up the screen buffer as big as it can get without overgrowing the screen or being a non-integer scale, then it's scaled up to the screen using bilinear)

it's basically the nostalgia filter from SCD 2011 but without it still being blurry even if it's scaled to a perfect multiple (or even worse, not scaled at all and is 1:1 scale), and it can help make the Vita port be in full screen without compromising pixel aspect ratio or creating visual bugs and making everything tiny

**Comment by ToruTheRedFox** [comment]
fixed conflict i think

**Comment by MGRich** [comment]
Reverting this, breaks Linux builds. Please fix Linux building and then make a new pull request.

**Comment by ToruTheRedFox** [comment]
What's the error? I don't have the Linux build tools so I don't know what the error is.

**Comment by Xeeynamo** [comment]
> What's the error? I don't have the Linux build tools so I don't know what the error is.

You might find [this](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/actions/runs/501720572) useful to know what the issue is. If you enable GitHub Actions on your fork you can also have a build status report there as well.

**Pull request merged**
