### PR TITLE
Updated Readme to add Linux & Windows MSYS2 instuctions, also added a "make clean" option to the make file.

### PR DESCRIPTION
**Pull request by chunkyjackson**
Pretty noob friendly instructions.

### CODE REVIEW

**Comment by chunkyjackson** [comment]
One note the "make clean" option will delete everything in the "bin" directory. so copy the exe/linux binary to another location.

**Comment by MGRich** [comment]
Solid instructions, even closes #99.

**Review by MGRich — APPROVED** [review]

**Comment by chunkyjackson** [comment]
This is the same for Sonic CD just need to add libtheora to the MSYS2 and Linux instructions.

**Comment by DilithiumNitrate** [comment]
Could you do a small change to the README? Specifically the line that tells you what dependencies to install on Arch Linux – the problem is where it tells you to `sudo pacman -Sy` the required packages. It's always recommended _not_ to do this, since [as explained here on the Arch Wiki](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported), Arch Linux does not support partial upgrades, unlike distros like Void or Debian, which keep copies of different versions of libraries if one is incompatible with another. Could you replace `sudo pacman -Sy` with `sudo pacman -S` in that part of the README?

**Comment by DilithiumNitrate** [comment]
Oh, and one more thing – you should add a Makefile option for compiling for MINGW (maybe two separate for 32-bit and 64-bit), to set the `-mwindows` linker flag in `CFLAGS` and `CXXFLAGS`, (equivalent to setting the subsystem to Windows in a Visual C/C++ project), and set `CC` and `CXX` to the MinGW compilers instead of the default, which under MSYS2 is for targetting MSYS2 specifically, so you cannot run this game outside of MSYS2 if compiled in MSYS2 without setting CC and CXX.

**Pull request merged**
